"""jobify.shared.match_status — the canonical matches.status enum
(HUNT2 P0.5, session 47).

A DIFFERENT lifecycle from ``jobify.shared.match_state`` (matches.state,
the user's own new/seen/saved/dismissed/applied triage). ``status`` is
written once by the fan-out ladder (``jobify.hosted.fanout``) at scoring
time and says which stage a posting fell out at, or that it made it all
the way through:

    rejected_title | rejected_rubric | rejected_rerank | rejected_llm | surfaced

Three places must agree, pinned by tests/test_match_status_contract.py
(mirroring tests/test_match_state_contract.py's pattern):

    1. ``CANONICAL_MATCH_STATUSES`` here (the source of truth).
    2. ``match_status.json`` (generated artifact, next to this file).
    3. the ``matches_status_check`` CHECK constraint in
       ``jobify/migrations/0014_hunt2_funnel.sql``.

Changing the enum therefore means: edit the tuple, run
``python -m jobify.shared.match_status`` to regenerate
``match_status.json``, and update the ``matches_status_check`` block in
``0014_hunt2_funnel.sql``.
"""

from __future__ import annotations

import json
from pathlib import Path

# Funnel order, terminal ("made it") state last. Must match
# matches_status_check in 0014_hunt2_funnel.sql and match_status.json
# next to this file.
CANONICAL_MATCH_STATUSES: tuple[str, ...] = (
    "rejected_title",
    "rejected_rubric",
    "rejected_rerank",
    "rejected_llm",
    "surfaced",
)

MATCH_STATUS_JSON_PATH = Path(__file__).with_name("match_status.json")


def match_status_json_payload() -> dict:
    """The exact object serialized into match_status.json."""
    return {
        "$comment": (
            "GENERATED by `python -m jobify.shared.match_status` from "
            "jobify/shared/match_status.py — do not edit by hand."
        ),
        "canonical_match_statuses": list(CANONICAL_MATCH_STATUSES),
    }


def write_match_status_json() -> Path:
    """Regenerate match_status.json from the Python definition above."""
    MATCH_STATUS_JSON_PATH.write_text(
        json.dumps(match_status_json_payload(), indent=2) + "\n", encoding="utf-8"
    )
    return MATCH_STATUS_JSON_PATH


if __name__ == "__main__":
    print(f"wrote {write_match_status_json()}")
