"""jobify.shared.match_state — the canonical matches.state enum for the
hosted aggregator (H1).

This is a DIFFERENT lifecycle from ``jobify.shared.status`` (jobs.status).
That module stays untouched — the single-user pipeline's status machine
is off-limits here. Aggregator state lives entirely on the hosted
``matches`` table (user_id x posting_id):

    new -> seen -> saved | dismissed | applied

Three places must agree, pinned by tests/test_match_state_contract.py
(mirroring tests/test_status_contract.py's pattern):

    1. ``CANONICAL_MATCH_STATES`` here (the source of truth).
    2. ``match_state.json`` (generated artifact, next to this file).
    3. the ``matches_state_check`` CHECK constraint in
       ``jobify/migrations/0002_multitenant.sql``.

Changing the enum therefore means: edit the tuple, run
``python -m jobify.shared.match_state`` to regenerate
``match_state.json``, and update the ``matches_state_check`` block in
``0002_multitenant.sql``.
"""

from __future__ import annotations

import json
from pathlib import Path

# Aggregator match lifecycle, pipeline order, terminal states last. Must
# match matches_state_check in 0002_multitenant.sql and match_state.json
# next to this file.
CANONICAL_MATCH_STATES: tuple[str, ...] = (
    "new",
    "seen",
    "saved",
    "dismissed",
    "applied",
)

MATCH_STATE_JSON_PATH = Path(__file__).with_name("match_state.json")


def match_state_json_payload() -> dict:
    """The exact object serialized into match_state.json."""
    return {
        "$comment": (
            "GENERATED by `python -m jobify.shared.match_state` from "
            "jobify/shared/match_state.py — do not edit by hand."
        ),
        "canonical_match_states": list(CANONICAL_MATCH_STATES),
    }


def write_match_state_json() -> Path:
    """Regenerate match_state.json from the Python definition above."""
    MATCH_STATE_JSON_PATH.write_text(
        json.dumps(match_state_json_payload(), indent=2) + "\n", encoding="utf-8"
    )
    return MATCH_STATE_JSON_PATH


if __name__ == "__main__":
    print(f"wrote {write_match_state_json()}")
