"""jobify.shared.status — the canonical jobs.status enum, single source
of truth for both repos.

Session E wiring:
    - ``CANONICAL_STATUSES`` here is THE definition. ``jobify.db``
      validates every transition against it.
    - ``status.json`` (next to this file, checked into the repo) is the
      generated artifact the portfolio dashboard consumes — its
      ``scripts/gen-status-types.mjs`` turns it into the ``JobStatus``
      TypeScript union, and its build prechain fails if the two drift.
    - The Postgres CHECK constraint (``jobs_status_check``, re-asserted
      by ``jobify/tailor/scripts/011_canonical_status.sql``) carries the
      same list.

Changing the enum therefore means: edit this tuple, run
``python -m jobify.shared.status`` to regenerate ``status.json``, write
a new SQL migration, and re-run the portfolio's ``npm run gen:status``.
Both CIs fail loudly until all four agree — that's the point.

``LEGACY_STATUS_MAP`` records how the retired pre-M-2 values map onto the
canonical lifecycle. It exists for documentation and for migration
tooling; no runtime code path reads or writes legacy values anymore.
"""

from __future__ import annotations

import json
from pathlib import Path

# M-2 canonical lifecycle (career-ops alignment). Order is pipeline order,
# terminal states last. Must match jobs_status_check in Postgres and
# status.json next to this file.
CANONICAL_STATUSES: tuple[str, ...] = (
    "discovered",
    "new",
    "approved",
    "preparing",
    "ready_for_review",
    "prefilling",
    "awaiting_human_submit",
    "applied",
    "failed",
    "skipped",
    "expired",
    "ignored",
)

# Retired pre-M-2 values -> canonical equivalents. Mirrors the mapping in
# 011_canonical_status.sql (see that file for the rationale per row).
LEGACY_STATUS_MAP: dict[str, str] = {
    "ready_to_submit": "ready_for_review",
    "tailored": "ready_for_review",
    "needs_review": "ready_for_review",
    "submit_confirmed": "awaiting_human_submit",
    "submitting": "prefilling",
    "submitted": "applied",
}

STATUS_JSON_PATH = Path(__file__).with_name("status.json")


def status_json_payload() -> dict:
    """The exact object serialized into status.json."""
    return {
        "$comment": (
            "GENERATED by `python -m jobify.shared.status` from "
            "jobify/shared/status.py — do not edit by hand. Consumed by "
            "the portfolio repo's scripts/gen-status-types.mjs."
        ),
        "canonical_statuses": list(CANONICAL_STATUSES),
        "legacy_status_map": LEGACY_STATUS_MAP,
    }


def write_status_json() -> Path:
    """Regenerate status.json from the Python definition above."""
    STATUS_JSON_PATH.write_text(
        json.dumps(status_json_payload(), indent=2) + "\n", encoding="utf-8"
    )
    return STATUS_JSON_PATH


if __name__ == "__main__":
    print(f"wrote {write_status_json()}")
