import yaml from "js-yaml";
import { buildPortalsDoc } from "./portalsSeed";

// The eight user-layer files, matching the `profiles.doc` JSONB contract
// (jobify/profile_loader.py::DOC_FILENAMES). Keep this list in the same
// order as that module.
export const DOC_FILENAMES = [
  "profile.yml",
  "thesis.md",
  "voice-profile.md",
  "article-digest.md",
  "learned-insights.md",
  "cv.md",
  "disqualifiers.yml",
  "portals.yml",
] as const;

export interface LocationAndCompensation {
  base?: string;
  remote_acceptable?: boolean;
  in_person_acceptable?: string;
  relocation?: string;
  current_comp_usd?: number;
  target_comp_usd?: string;
}

export interface ResumeStageData {
  cv_markdown: string;
  key_technical_skills?: string[];
  background_summary?: string;
}

// ONB-A (§2 stage 1): the anchor form's two required fields + optional
// tenure, OR the "I'm between roles" free-text escape path — never both.
// Written server-side (POST /api/onboarding/anchor), never by a model tool.
export interface AnchorStageData {
  current_title?: string;
  current_company?: string;
  years_in_role?: string;
  free_text?: string;
}

// ONB-A (§2 stage 2): `prompts` is set by the generation turn
// (runCalibrationGeneration) before any answer exists; the other four
// fields are set by the ingest turn's record_calibration tool call.
export interface CalibrationStageData {
  prompts?: string[];
  skills?: string[];
  evidence?: string[];
  range_statement?: string;
  background_summary?: string;
}

export interface IdentityStageData {
  name: string;
  email: string;
  phone?: string;
  location_base?: string;
  linkedin?: string;
  website?: string;
  github?: string;
  location_and_compensation?: LocationAndCompensation;
}

export interface TargetingTier {
  key: string;
  label: string;
  notes?: string;
  reference_role?: string;
}

export interface TargetingStageData {
  tiers: TargetingTier[];
  dream_companies?: string[];
  hard_disqualifiers: string[];
  soft_concerns: string[];
  degree_gate?: string;
  thesis_summary: string;
}

export interface ExtractedState {
  anchor?: AnchorStageData;
  calibration?: CalibrationStageData;
  resume?: ResumeStageData;
  identity?: IdentityStageData;
  targeting?: TargetingStageData;
}

// v1 deliberately never asks for application_defaults (the aggregator
// never fills forms — HOSTED_AGGREGATOR_PLAN.md §7, session prompt task
// 3). The schema still marks these keys as required at the top level
// (onboarding/schema/profile.schema.json), so they're written present but
// blank: presence, not content, is what the validator (and downstream
// loaders) check.
const BLANK_APPLICATION_DEFAULTS = {
  work_authorization: "",
  visa_sponsorship_needed: false,
  earliest_start_date: "",
  relocation_willingness: "",
  in_person_willingness: "",
  ai_policy_ack: "",
  previous_interview_with_company: {},
};

function buildProfileYaml(extracted: ExtractedState): string {
  const identity = extracted.identity;
  const targeting = extracted.targeting;
  const resume = extracted.resume;
  const calibration = extracted.calibration;

  const whatHeIsLookingFor: Record<string, unknown> = {};
  for (const tier of targeting?.tiers ?? []) {
    whatHeIsLookingFor[tier.key] = {
      label: tier.label,
      ...(tier.notes ? { notes: tier.notes } : {}),
      ...(tier.reference_role ? { reference_role: tier.reference_role } : {}),
    };
  }

  // ONB-A: when no resume was given, background_summary and
  // key_technical_skills fall back to the calibration stage's synthesis
  // (the calibration ingest prompt already has anchor context, so its
  // background_summary already reads as if it knows the anchored role).
  const backgroundSummary = resume?.background_summary ?? calibration?.background_summary;
  const keyTechnicalSkills = resume?.key_technical_skills?.length
    ? resume.key_technical_skills
    : calibration?.skills;

  const doc: Record<string, unknown> = {
    identity: {
      name: identity?.name ?? "",
      email: identity?.email ?? "",
      ...(identity?.phone ? { phone: identity.phone } : {}),
      ...(identity?.location_base ? { location_base: identity.location_base } : {}),
      ...(identity?.linkedin ? { linkedin: identity.linkedin } : {}),
      ...(identity?.website ? { website: identity.website } : {}),
      ...(identity?.github ? { github: identity.github } : {}),
    },
    ...(backgroundSummary ? { background_summary: backgroundSummary } : {}),
    ...(identity?.location_and_compensation ? { location_and_compensation: identity.location_and_compensation } : {}),
    ...(Object.keys(whatHeIsLookingFor).length ? { what_he_is_looking_for: whatHeIsLookingFor } : {}),
    ...(keyTechnicalSkills?.length ? { key_technical_skills: keyTechnicalSkills } : {}),
    application_defaults: BLANK_APPLICATION_DEFAULTS,
  };

  const header =
    "# profile.yml — generated by the hosted onboarding chat.\n" +
    "# application_defaults is intentionally blank: the aggregator never fills\n" +
    "# forms, so the interview never asks for work authorization / visa /\n" +
    "# start date / relocation-for-forms / AI-policy-ack. Hand-edit any field;\n" +
    "# code never overwrites this file after this initial write — EXCEPT\n" +
    "# web/lib/profile/regenerateCv.ts (ONB-A decision #3), which may rewrite\n" +
    "# background_summary alone if a user uploads a resume after skipping it\n" +
    "# during onboarding. Every other field, and every other file, is still a\n" +
    "# one-time write.\n\n";

  return header + yaml.dump(doc, { noRefs: true, lineWidth: -1 });
}

/**
 * ONB-A §2 stage 3: when the resume stage is skipped, cv.md is synthesized
 * from anchor + calibration at buildDoc time rather than left empty, so
 * downstream (tailor-era) code always has *something* to select from. The
 * leading heading doubles as a provenance marker distinguishing this from a
 * real uploaded resume.
 */
function buildSynthesizedCv(anchor?: AnchorStageData, calibration?: CalibrationStageData): string {
  const lines: string[] = ["# CV — assembled from onboarding interview (no resume provided)", ""];

  const roleLine =
    anchor?.current_title && anchor?.current_company
      ? `## ${anchor.current_title} — ${anchor.current_company}${anchor.years_in_role ? ` (${anchor.years_in_role})` : ""}`
      : anchor?.free_text
        ? `## ${anchor.free_text}`
        : "## Background";
  lines.push(roleLine, "");

  const evidence = calibration?.evidence ?? [];
  if (evidence.length) {
    for (const item of evidence) lines.push(`- ${item}`);
    lines.push("");
  }

  const skills = calibration?.skills ?? [];
  if (skills.length) {
    lines.push("## Skills", "", skills.join(", "), "");
  }

  return lines.join("\n").trim() + "\n";
}

function buildThesisMd(targeting?: TargetingStageData): string {
  if (!targeting) return "";
  const lines: string[] = ["# Hunting thesis", ""];
  lines.push(targeting.thesis_summary.trim(), "");
  if (targeting.tiers.length) {
    lines.push("## Tiers", "");
    for (const tier of targeting.tiers) {
      lines.push(`- **${tier.label}**${tier.notes ? ` — ${tier.notes}` : ""}`);
    }
    lines.push("");
  }
  if (targeting.hard_disqualifiers.length) {
    lines.push("## Hard constraints", "");
    for (const d of targeting.hard_disqualifiers) lines.push(`- ${d}`);
    lines.push("");
  }
  if (targeting.degree_gate) {
    lines.push("## Degree gate", "", targeting.degree_gate, "");
  }
  return lines.join("\n").trim() + "\n";
}

function buildDisqualifiersYaml(targeting?: TargetingStageData): string {
  return yaml.dump(
    {
      hard_disqualifiers: targeting?.hard_disqualifiers ?? [],
      soft_concerns: targeting?.soft_concerns ?? [],
    },
    { noRefs: true, lineWidth: -1 }
  );
}

function buildPortalsYaml(targeting?: TargetingStageData, anchor?: AnchorStageData): string {
  return yaml.dump(
    buildPortalsDoc(
      {
        tiers: targeting?.tiers ?? [],
        hard_disqualifiers: targeting?.hard_disqualifiers,
        // Threaded through so it's no longer dropped on the floor — the
        // sync placeholder here still ships empty company lists (network
        // probing doesn't belong on this hot path); the real dream-company
        // seed is assembled by portalsSeed.ts's seedPortalsCompanies.
        dream_companies: targeting?.dream_companies,
      },
      anchor?.current_title
    ),
    { noRefs: true, lineWidth: -1 }
  );
}

/**
 * Assembles the eight-file `profiles.doc` JSONB payload from the
 * interview's accumulated `extracted` state. Files the v1 interview
 * doesn't cover (voice-profile.md, article-digest.md, learned-insights.md
 * — voice/proof-points/archetypes are tailor-era, out of v1 scope per the
 * session prompt) ship as valid minimal (empty) stubs.
 */
export function buildProfileDoc(extracted: ExtractedState): Record<string, string> {
  return {
    "profile.yml": buildProfileYaml(extracted),
    "thesis.md": buildThesisMd(extracted.targeting),
    "voice-profile.md": "",
    "article-digest.md": "",
    "learned-insights.md": "",
    "cv.md":
      extracted.resume?.cv_markdown ??
      (extracted.anchor ? buildSynthesizedCv(extracted.anchor, extracted.calibration) : ""),
    "disqualifiers.yml": buildDisqualifiersYaml(extracted.targeting),
    "portals.yml": buildPortalsYaml(extracted.targeting, extracted.anchor),
  };
}
