import { describe, expect, it } from "vitest";
import yaml from "js-yaml";
import { regenerateCv } from "./regenerateCv";

const PROFILE_YAML =
  "# profile.yml — generated by the hosted onboarding chat.\n" +
  "# application_defaults is intentionally blank: the aggregator never fills\n" +
  "# forms, so the interview never asks for work authorization / visa /\n" +
  "# start date / relocation-for-forms / AI-policy-ack. Hand-edit any field;\n" +
  "# code never overwrites this file after this initial write — EXCEPT\n" +
  "# web/lib/profile/regenerateCv.ts (ONB-A decision #3), which may rewrite\n" +
  "# background_summary alone if a user uploads a resume after skipping it\n" +
  "# during onboarding. Every other field, and every other file, is still a\n" +
  "# one-time write.\n\n" +
  yaml.dump({
    identity: { name: "Alex Quinn", email: "alex@example.com" },
    background_summary: "Assembled from onboarding interview, no resume given.",
    key_technical_skills: ["Go", "Postgres"],
    application_defaults: { work_authorization: "" },
  });

function baseDoc(): Record<string, string> {
  return {
    "profile.yml": PROFILE_YAML,
    "thesis.md": "# Hunting thesis\n\nWants backend roles.\n",
    "voice-profile.md": "",
    "article-digest.md": "",
    "learned-insights.md": "",
    "cv.md": "# CV — assembled from onboarding interview (no resume provided)\n\n## Background\n",
    "disqualifiers.yml": "hard_disqualifiers: []\nsoft_concerns: []\n",
    "portals.yml": "greenhouse:\n  companies: []\n",
  };
}

describe("regenerateCv", () => {
  it("rewrites cv.md with the freshly extracted resume text", async () => {
    const doc = baseDoc();
    const updated = await regenerateCv(doc, "Alex Quinn resume text...", {
      runExtraction: async () => ({ cv_markdown: "# Alex Quinn\n\n## Experience\n\n- Real resume content." }),
    });
    expect(updated["cv.md"]).toBe("# Alex Quinn\n\n## Experience\n\n- Real resume content.");
  });

  it("preserves every other file untouched", async () => {
    const doc = baseDoc();
    const updated = await regenerateCv(doc, "resume text", {
      runExtraction: async () => ({ cv_markdown: "# New CV" }),
    });
    expect(updated["thesis.md"]).toBe(doc["thesis.md"]);
    expect(updated["disqualifiers.yml"]).toBe(doc["disqualifiers.yml"]);
    expect(updated["portals.yml"]).toBe(doc["portals.yml"]);
    expect(updated["voice-profile.md"]).toBe(doc["voice-profile.md"]);
  });

  it("does not mutate the original doc object", async () => {
    const doc = baseDoc();
    const frozenCv = doc["cv.md"];
    await regenerateCv(doc, "resume text", { runExtraction: async () => ({ cv_markdown: "# New CV" }) });
    expect(doc["cv.md"]).toBe(frozenCv);
  });

  it("rewrites ONLY background_summary in profile.yml when the extraction provides one, preserving every other key", async () => {
    const doc = baseDoc();
    const updated = await regenerateCv(doc, "resume text", {
      runExtraction: async () => ({
        cv_markdown: "# New CV",
        background_summary: "Backend engineer with a real resume on file now.",
      }),
    });
    const parsed = yaml.load(updated["profile.yml"].replace(/^#.*\n/gm, "")) as Record<string, unknown>;
    expect(parsed.background_summary).toBe("Backend engineer with a real resume on file now.");
    expect(parsed.identity).toEqual({ name: "Alex Quinn", email: "alex@example.com" });
    expect(parsed.key_technical_skills).toEqual(["Go", "Postgres"]);
  });

  it("preserves the profile.yml header comment block across a background_summary rewrite", async () => {
    const doc = baseDoc();
    const updated = await regenerateCv(doc, "resume text", {
      runExtraction: async () => ({ cv_markdown: "# New CV", background_summary: "New summary." }),
    });
    expect(updated["profile.yml"]).toContain("# profile.yml — generated by the hosted onboarding chat.");
    expect(updated["profile.yml"]).toContain("regenerateCv.ts (ONB-A decision #3)");
  });

  it("leaves profile.yml completely untouched when the extraction yields no background_summary", async () => {
    const doc = baseDoc();
    const updated = await regenerateCv(doc, "resume text", {
      runExtraction: async () => ({ cv_markdown: "# New CV" }),
    });
    expect(updated["profile.yml"]).toBe(doc["profile.yml"]);
  });
});
